version: "2"
volumes:
  mobius-data:
  mobius-licence:
  node-red-assets:
  node-red-data:

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - mobius
      - node-red

  mobius:
    image: ghcr.io/mobiusflow/balena_rpi4_mobiusflow-v2-le:2.3.2_2.3.1
    privileged: true
    restart: always
    ports:
      - 443:443
      - 502:502
      - 1883:1883
      - 4840:4840
      - "5568:5568/udp"
      - 8443:8443
      - 8883:8883
      - 9081:9081
      - 10502:10502
      - 10001:10001
      - 30815:30815
      - 30883:30883
    volumes:
      - mobius-data:/data
      - mobius-licence:/.licence
    labels:
      io.resin.features.supervisor-api: "1"

  node-red:
    image: mobiusflow/node-red:latest
    container_name: node-red
    privileged: false
    restart: always
    ports:
      - 1880:1880
    volumes:
      - node-red-assets:/assets
      - mobius-data:/data

  toolbox:
    container_name: toolbox
    image: mobiusflow/mobiusflow-toolbox:latest
    privileged: false
    restart: always
    ports:
      - 8080:8080

  manage:
    image: ghcr.io/mobiusflow/balena_rpi4_manage-v2:2.3.2
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - mobius-data:/data
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
